version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  app:
    container_name: test
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
